# Generated by Django 4.0.3 on 2022-05-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
