# Generated by Django 4.0.3 on 2022-04-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_quantity',
            new_name='product_qty',
        ),
    ]
