# Generated by Django 3.2.3 on 2022-05-02 15:39

import django.core.validators
from django.db import migrations, models
import embed_video.fields
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to=store.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
